# Generated by Django 2.1.5 on 2019-01-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190112_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('OT', 'others'), ('PP', 'Passport'), ('ID', 'Identity card')], max_length=2),
        ),
    ]
