# Generated by Django 2.1.5 on 2019-01-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190112_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('PP', 'Passport'), ('ID', 'Identity card'), ('OT', 'others')], max_length=2),
        ),
    ]
