# Generated by Django 2.1.5 on 2019-01-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190112_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('OT', 'others'), ('ID', 'Identity card'), ('PP', 'Passport')], max_length=2),
        ),
    ]
