# Generated by Django 2.1.5 on 2019-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190128_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='doc',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
