# Generated by Django 2.1.5 on 2019-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190205_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dtype',
            field=models.CharField(choices=[('OT', 'others'), ('ID', 'Identity card'), ('PP', 'Passport')], max_length=2),
        ),
    ]
